version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.2-stretch-node
        auth:
          username: pbhartianviamcom
          password: anviam#123  # context / project UI env-var reference
          
   executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

workflows:
  test_my_app:
    jobs:
      - test
