version: 2

orbs:
  ruby: circleci/ruby@2.7.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          POSTGRES_USER: anviam
          POSTGRES_DB: store_test
          POSTGRES_PASSWORD: anviam
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: anviam
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      # - ruby/rspec-test
      # - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
