version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.2-stretch-node
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - run:
        command: bundle install --path vendor/bundle
workflows:
  version: 2
  workflow:
    jobs:
    - build